// Generated by CoffeeScript 1.3.3
(function() {
  var Gurli;

  Gurli = (function() {

    function Gurli() {
      var pairArray, pairIndex, paramsArray;
      this.baseUrl = window.location.href.split("?")[0];
      paramsArray = window.location.href.split("?")[1];
      paramsArray = paramsArray ? paramsArray.split("&") : [];
      this.params = {};
      for (pairIndex in paramsArray) {
        pairArray = paramsArray[pairIndex].split("=");
        this.params[decodeURIComponent(pairArray[0])] = decodeURIComponent(pairArray[1]);
      }
    }

    Gurli.prototype.setParam = function(name, value) {
      return this.params[name] = value;
    };

    Gurli.prototype.getParam = function(name) {
      return this.params[name];
    };

    Gurli.prototype.removeParam = function(name) {
      return delete this.params[name];
    };

    Gurli.prototype.clearParams = function() {
      this.params = [];
    };

    Gurli.prototype.setBaseUrl = function(newUrl) {
      return this.baseUrl = encodeURI(newUrl);
    };

    Gurli.prototype.toURL = function() {
      var property, urlString;
      urlString = this.baseUrl + "?";
      for (property in this.params) {
        urlString = urlString + encodeURIComponent(property) + "=" + encodeURIComponent(this.params[property]) + "&";
      }
      return urlString.slice(0, -1);
    };

    Gurli.prototype.goto = function() {
      return window.location = this.toURL();
    };

    return Gurli;

  })();

  window.Gurli = Gurli;

}).call(this);
